{{- /* Render Istio ServiceEntries */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: allow-minio-api-9000-for-velero
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
    - 'minio-api.{{ $.Values.domain }}'
  location: MESH_EXTERNAL
  exportTo:
  - "."
  ports:
    - number: 9000
      name: minio
      protocol: TCP
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: allow-minio-api-https-for-velero
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
    - 'minio-api.{{ $.Values.domain }}'
  location: MESH_EXTERNAL
  exportTo:
  - "."
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
---
{{- end -}}
